[[pages]]
path = "src/pages/root.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "src/pages/category.py"
name = "Category"
icon = "ğŸ“š"

[[pages]]
path = "src/pages/product.py"
name = "Product"
icon = "â™¨ï¸"

